version: "3"

services:
   php:
      build: ./php
      depends_on:
         - sql
      env_file:
         - ./docker-compose.env
      ports:
         - 8081:80
      volumes:
         - ./php/Classes:/var/www/Classes
         - ./php/public_html:/var/www/public_html
         - ./php/lib:/var/www/lib
   app:
      build: ./app
      depends_on:
         - php
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./app/nginx.conf:/etc/nginx/conf.d/default.conf
         - ./public_html:/usr/share/nginx/html
         - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/abqcookbook.com/fullchain.pem:/etc/letsencrypt/live/abqcookbook.com/fullchain.pem
         - /docker-volumes/pwp/etc/letsencrypt/live/abqcookbook.com/privkey.pem:/etc/letsencrypt/live/abqcookbook.com/privkey.pem

   sql:
      build: ./sql
      volumes:
         - cookbook-sql:/var/lib/mysql
      env_file:
         - ./docker-compose.env
volumes:
   cookbook-sql:

